### ISSUE TITLE
Customize daguerre's directory path

### ISSUE THREAD

**Issue by fitodic** [littleweaver/django-daguerre#102]
The current save plan is to save image variations under a [path](https://github.com/littleweaver/django-daguerre/blob/master/daguerre/models.py#L107) based on the date they were created. This behaviour is more than satisfactory in most cases, such as using the library from the beginning of a project or incorporating it in the middle of a project. However, projects get migrated.

One issue we have encountered is the recreation of a large amount of image variations from the original set of images in a single run, i.e. on the same day. Theoretically, an unlimited amount of files can be stored on a [Linux/Unix](http://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory) OS, but a large amount of files in a single directory inevitably slows down the filesystem search. Although rare, it is a problem.

To tackle this issue, the option of modifying the storage path through the project's settings could be added to the library. The current setup would remain the default option (e.g. *daguerre/2016/10/12/*), but the developers working on the project could opt for a more customized path. For instance, they could use hash subdirectories for saving image variations (e.g. */daguerre/ha/sh/dr/*). A working example is already implemented in our [fork](https://github.com/Styria-Digital/django-daguerre/blob/f292a6e1dc07564e16ba5260aed46b762cc2cb87/daguerre/models.py#L105).

What are your thoughts on the matter? I'd be happy to implement it and send you a pull request.

**Comment by melinath** [comment]
This would be a great change. It would be awesome to have a PR for it. A couple additional things:

* We'd like to switch over to hashes for everyone, rather than having a setting for it. It's just a better way to generate the folder hierarchy, because of the folder size issue. Old data will be preserved in the db if people want it to be.
* While we're at it, we could change the base folder from `daguerre` to `dg` - it's unlikely to be used by other applications and would free up space in the field for additional folder levels without needing to lengthen the field.

**Comment by fitodic** [comment]
Thanks for the feedback! Both of your requests have been taken into consideration and implemented. 
If you are OK with the proposed changes, that only leaves the matter of updating the documentation. Should I update it and add it to the #103 PR or you have something else in mind?

**Comment by melinath** [comment]
If there are docs changes they should be included in the same PR.
